base:
    su: "19061529"
    baseurl: "http://newjw.hdu.edu.cn"
  # baseurl: http://192.168.101.158
headers:
  Host: 
    - "newjw.hdu.edu.cn"
  Proxy-Connection: 
    - "keep-alive"
  Content-Length: 
    - "527"
  Accept: 
    - "application/json"
    - "text/javascript"
    - "*/*; q=0.01"
  X-Requested-With: 
    - "XMLHttpRequest"
  User-Agent: 
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52"
  Content-Type: 
    - "application/x-www-form-urlencoded;charset=UTF-8"
  Origin: 
    - "http://newjw.hdu.edu.cn"
  Referer: 
    - "http://newjw.hdu.edu.cn/jwglxt/xsxk/zzxkyzb_cxZzxkYzbIndex.html?gnmkdm=N253512&layout=default&su=19061529"
  Accept-Encoding:
    - "gzip"
    - "deflate"
  Accept-Language: 
    - "zh-CN"
    - "zh;q=0.9"
    - "en;q=0.8"
    - "en-GB;q=0.7"
    - "en-US;q=0.6"
  Cookie: 
    - "JSESSIONID=3C06D9A643093BC9C80F6A6E9DC767CF; route=c96cf3d2b06493f56fcb5bd7f7e8caa9"
body: "jxb_ids=5a1f85f5502e416e0fe18b9fb499d76988a0f45111f6e92589b320c62101fa0623218385b579e6ad58908255eed0ded2d4978b9c54390b2b2e55724426688158cb504cffed58df2b76a2203585e1879a36e979ef87141ae56f641747091e5ea6e225fcd31cbc901beb9be1d42a8b6c5da8dd352772890377f6d64acf5d05bf3e&kch_id=C0399021&kcmc=(C0399021)%E5%88%9B%E4%B8%9A%E5%9B%A2%E9%98%9F%E7%AE%A1%E7%90%86+-+1.0+%E5%AD%A6%E5%88%86&rwlx=2&rlkz=0&rlzlkz=1&sxbj=1&xxkbj=0&qz=0&cxbj=0&xkkz_id=C5C97F00AC26919BE0536264A8C08E79&njdm_id=2019&zyh_id=0527&kklxdm=10&xklc=2&xkxnm=2021&xkxqm=3"